"""Sphinx configuration for the FactorLasso documentation.

As in the qis documentation, the API reference is generated at build time rather than checked in.
``api.rst`` includes ``_generated/api_reference.rst``, written here from ``factorlasso.__all__`` and
the ownership recorded in ``tools/docs_inventory.json``:

1. one section per owning methodology article, in the order of the sidebar, each with a summary
   table and the documented objects, so every existing ``api.html#factorlasso.<name>`` anchor
   remains valid; and
2. a map of the ``LassoModel`` configuration parameters to the articles that explain them.

The generated file is git-ignored, so the reference cannot drift from the exports.
"""

import enum
import inspect
import json
import os
import sys

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10 metadata tests use the compatible parser.
    import tomli as tomllib
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parent
REPOSITORY_ROOT = DOCS_DIR.parent
sys.path.insert(0, str(REPOSITORY_ROOT / "src"))
sys.path.insert(0, str(DOCS_DIR / "_ext"))

project = "factorlasso"
author = "Artur Sepp and Mika Kastenholz"
copyright = "2026, Artur Sepp"
release = tomllib.loads(
    (REPOSITORY_ROOT / "pyproject.toml").read_text(encoding="utf-8")
)["project"]["version"]
version = release

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.viewcode",
    "numpydoc",
    "sphinxcontrib.mermaid",
    "factorlasso_indexing",
]

# Articles are portable Markdown; the API entry and task guides stay RST.
# Dollar math keeps article source readable in MyST, GitHub Markdown and VS Code alike.
myst_enable_extensions = ["dollarmath"]
# Resolve ordinary Markdown section links with GitHub-compatible heading fragments.
myst_heading_anchors = 4
# A ```mermaid fence renders as a diagram in Sphinx and natively on GitHub.
myst_fence_as_directive = ["mermaid"]
# Keep each diagram's own aspect ratio; the extension's fixed 500px box shrinks tall diagrams.
mermaid_height = "auto"

root_doc = "index"
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
exclude_patterns = ["_build", "_generated", "Thumbs.db", ".DS_Store"]
templates_path = ["_templates"]
nitpicky = False
autodoc_typehints = "description"
autodoc_member_order = "bysource"
# Summary tables only: the objects are documented on api.html itself, keeping their anchors.
autosummary_generate = False
numpydoc_show_class_members = False
doctest_test_doctest_blocks = ""

GOOGLE_SITE_VERIFICATION = "cddUZk3Gsd1MySw42Rwuq_rMzUDcMNkJWekObx-QS9Y"

# Docstrings write |t| and |beta| as plain text; define them so RST does not read references.
rst_prolog = """
.. |t| replace:: t
.. |beta| replace:: beta
"""

html_theme = "furo"
html_title = "factorlasso - sparse factor-model estimation"
# The verification tag is emitted by _templates/base.html on every page, Markdown included.
html_context = {"google_site_verification": GOOGLE_SITE_VERIFICATION}
html_baseurl = os.environ.get(
    "READTHEDOCS_CANONICAL_URL",
    "https://factorlasso.readthedocs.io/en/latest/",
)

linkcheck_anchors = True
# SSRN answers automated requests with 403 Forbidden; its links are checked by hand, as in
# OptimalPortfolios.
linkcheck_ignore = [
    r"https://(?:www\.)?ssrn\.com/.*",
    r"https://papers\.ssrn\.com/.*",
]
# Archived research links occasionally exceed 20 seconds; keep checks bounded and retry once.
linkcheck_timeout = 30
linkcheck_retries = 2
# Retry timeouts too; persistent failures still fail the link check after both attempts.
linkcheck_report_timeouts_as_broken = True

API_HEADER = """..
   Generated by docs/conf.py from factorlasso.__all__ and tools/docs_inventory.json.
   Do not edit by hand; the file is git-ignored.

"""


def _page_title(relative: str, planned: dict) -> tuple[str, bool]:
    """Return the H1 title of an inventoried page, and whether the page exists.

    Parameters
    ----------
    relative : str
        Repository-relative page path, such as ``docs/sparse_factor_model.md``.
    planned : dict
        Planned articles of the inventory, which supply titles of pages not yet written.
    """
    path = REPOSITORY_ROOT / relative
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip(), True
    return planned.get(relative, {}).get("title", relative), False


def _article_reference(relative: str, planned: dict) -> str:
    """Return an RST link to an existing article, or the plain title of a planned one."""
    title, exists = _page_title(relative, planned)
    if exists:
        docname = Path(relative).relative_to("docs").with_suffix("").as_posix()
        return f":doc:`{title} </{docname}>`"
    return f"*{title}* (planned article)"


def _format_default(value) -> str:
    """Render a dataclass default the way a reader would type it."""
    if isinstance(value, enum.Enum):
        return f"{type(value).__name__}.{value.name}"
    return repr(value)


def _heading(title: str, underline: str) -> str:
    return f"{title}\n{underline * len(title)}\n\n"


def _write_api_reference(target: Path = DOCS_DIR / "_generated") -> Path:
    """Write ``api_reference.rst`` from the exports and the article ownership.

    Parameters
    ----------
    target : Path, default ``docs/_generated``
        Output directory; tests pass a temporary directory.

    Returns
    -------
    Path
        The written file.
    """
    import factorlasso
    from factorlasso import LassoModel

    inventory = json.loads(
        (REPOSITORY_ROOT / "tools" / "docs_inventory.json").read_text(encoding="utf-8")
    )
    planned = inventory["planned"]
    exported = list(factorlasso.__all__)
    owned = [name for names in inventory["symbols"].values() for name in names]
    missing = sorted(set(exported) - set(owned))
    if missing:
        raise RuntimeError(f"Public names without an owning article: {missing}")

    lines = [API_HEADER]
    signature = inspect.signature(LassoModel).parameters
    lines.append(_heading("LassoModel parameters by topic", "-"))
    lines.append(
        "Each configuration parameter of :class:`~factorlasso.LassoModel` is explained in one "
        "article. The table lists them by article, with their defaults.\n\n"
        ".. list-table::\n   :header-rows: 1\n   :widths: 32 68\n\n"
        "   * - Article\n     - Parameters and defaults\n"
    )
    for article, names in inventory["parameters"].items():
        entries = ", ".join(
            f"``{name}={_format_default(signature[name].default)}``" for name in names
        )
        lines.append(f"   * - {_article_reference(article, planned)}\n     - {entries}\n")
    fitted = [name for name in signature if name.endswith("_")]
    lines.append(
        "\nThe signature also lists "
        f"{len(fitted)} fields that end with an underscore ("
        + ", ".join(f"``{name}``" for name in fitted)
        + "). They hold the state that ``fit`` sets and are not configuration.\n\n"
    )

    for article, names in inventory["symbols"].items():
        title, _ = _page_title(article, planned)
        lines.append(_heading(title, "-"))
        lines.append(f"Explained in {_article_reference(article, planned)}.\n\n")
        lines.append(".. autosummary::\n   :nosignatures:\n\n")
        # api.rst declares the factorlasso module, so the summary uses the short names
        lines.extend(f"   {name}\n" for name in names)
        lines.append("\n")
        for name in names:
            obj = getattr(factorlasso, name)
            if inspect.isclass(obj):
                lines.append(
                    f".. autoclass:: factorlasso.{name}\n"
                    "   :members:\n   :show-inheritance:\n   :member-order: bysource\n\n"
                )
            else:
                lines.append(f".. autofunction:: factorlasso.{name}\n\n")

    target.mkdir(parents=True, exist_ok=True)
    output = target / "api_reference.rst"
    output.write_text("".join(lines), encoding="utf-8")
    return output


def setup(app) -> None:
    """Generate the API reference before Sphinx reads the sources."""
    _write_api_reference()
